### ISSUE TITLE
Call to undefined method TYPO3\CMS\Core\Imaging\IconRegistry::getDeprecatedIcons() 

### ISSUE THREAD

**Issue by jimihuy** [TYPO3/styleguide#111]
I use TYPO3 8.7.10

https://github.com/TYPO3/styleguide/blob/master/Classes/Controller/StyleguideController.php#L189

**Comment by rawsta** [comment]
I get the same error in TYPO§ 8.7.16

**Comment by visualmovement** [comment]
same here with TYPO3 8.7.18 any chance for a fix?

**Comment by tmotyl** [comment]
Can any of you provide a pull request? This would be helpful. Thanks.

**Comment by visualmovement** [comment]
got it to work by using the 8 branch and not the master
