### ISSUE TITLE
Version 8 not available on TER

### ISSUE THREAD

**Issue by cweiske** [TYPO3/styleguide#116]
The latest "styleguide" version available on TER is 7.6, which I cannot use on TYPO3 v8.

https://extensions.typo3.org/extension/styleguide/

**Comment by lolli42** [comment]
Quite frankly, we're currently too lazy to release to TER and nobody did set up some automatic thing up for it, yet, either. We'll not pick that up if not someone puts time into that and prepares a solution that works automatically as soon as we tag a new version.
We more or less expect that most devs interested in this extension fetch it as a require-dev dependency via composer. We do tags and this triggers packagist releases. Other people may just clone that extension to typo3conf/ext to fetch it.
