### ISSUE TITLE
status-reference-hard not registered

### ISSUE THREAD

**Issue by froemken** [TYPO3/styleguide#127]
Hello,

if I open styleguide and click on Icons I get following error:

Oops, an error occurred!
Icon with identifier "status-reference-hard" is not registered"

I have searched a little bit in core and found out, that this icon is part of impext. After enabling this extension Icon-View works as expected.

Stefan

**Comment by lolli42** [comment]
weird. thx for htis report. needs investigation.

**Comment by lolli42** [comment]
That's a core bug, see https://forge.typo3.org/issues/92021. Will be fixed in v10 since the issue is not critical enough for v9 anymore. For v9, please just load ext:impexp to circumvent the issue.
Will close here.
