### ISSUE TITLE
Unknown column 'pid' in 'field list'

### ISSUE THREAD

**Issue by Geddo** [TYPO3/styleguide#129]
Just installed the latest typo3 v8 and styleguide via composer, did an db-compare with the result:
	
`Oops, an error occurred!
An exception occurred while executing 'SELECT `uid` FROM `tx_styleguide_elements_basic` WHERE (`tx_styleguide_elements_basic`.`pid` = 5) AND ((`tx_styleguide_elements_basic`.`deleted` = 0) AND ((`tx_styleguide_elements_basic`.`t3ver_wsid` = 0) OR (`tx_styleguide_elements_basic`.`t3ver_state` <= 0)))': Unknown column 'uid' in 'field list'`

What I'm missing?

**Comment by lolli42** [comment]
Probably just a missing version restriction: With core v8 you need a 8.x.y version of styleguide - it may be possible some 9.x.y tags have no proper composer.json restriction and one of these has been fetched for you. Try switching to "typo3/cms-styleguide": "^8.0.15" in your composer.json.

**Comment by lolli42** [comment]
Did this issue resolve on your side?
