### ISSUE TITLE
Extension listed as outdated in TYPO3 Extension Repository

### ISSUE THREAD

**Issue by sypets** [TYPO3/styleguide#136]
I already raised the issue in Slack. 

1. Page in TER https://extensions.typo3.org/extension/styleguide/ lists extension as outdated.

![styleguide-ter](https://user-images.githubusercontent.com/13206455/56791803-48af8400-6808-11e9-971f-0971c6ad3b45.png)

2. The current installation instructions in Readme.md do not work for non-composer installations:

> Head to TYPO3 backend > Extension Manager > Get Extensions. Search for and install extension key „styleguide“. Activate Styleguide extension within TYPO3 backend in Extension Manager.

3. Not possible to install via extension manager on non Composer based installations

4. Additionally, the Composer command is usually listed in the TYPO3 Extension Repository. For
styleguide, it is not. 

Since this extension is recommended in the documentation and might be used by beginners, I find current situation a little unfortunate and not new-user-friendly:

Why is extension listed as outdated? No clarification on Readme.md here or in TER. No installation instructions in TER. No possibility to install via extension manager on non Composer installations. Misleading information in this Readme.md.

---

I would create a PR myself to help, but not sure about what would be correct.

**Comment by lolli42** [comment]
Clearified in README.md that ext:styleguide is currently not released to TER.
