### ISSUE TITLE
TCA test content records aren't generated

### ISSUE THREAD

**Issue by vaxul** [TYPO3/styleguide#143]
# Bug Report

## Prerequisites

* [x]  Can you reproduce the problem on TYPO3 v10.4 LTS?
* [x] Can you reproduce the problem on TYPO3 v9.5 LTS?

## Description

Within the styleguide backend module beneath `TCA / Records` it is the possible to generate a page tree with default records and demo data, which seems not to work as intended.

## Steps to Reproduce

1. Checkout latest TYPO3 branch for v9 or v10 from git://git.typo3.org/Packages/TYPO3.CMS.git
2. Run TYPO3 with current DDEV version.
3. Install styleguide extension from the extension manager.
4. Open up the Styleguide backend module and go to `TCA / Records` and click `Create styleguide page tree with data` and wait.
5. Open up the Pages backend module and expand the page tree `styleguide TCA demo` and inspect the pages.

**Expected behavior:**
The pages within `styleguide TCA demo` are filled with default content element records. 

**Actual behavior:**
All pages within `styleguide TCA demo` are empty.

## Versions
typo3/cms-styleguide 9.2.4

**Comment by maddy2101** [comment]
Hi, thank you for the report, but I need to disappoint you.

styleguide does not create content elements, but records. You can see those via the list module.

I close the ticket because you reported a misunderstanding :) The extension is not misbehaving.

**Comment by vaxul** [comment]
Thanks for the clarification. 👍
