### ISSUE TITLE
Typo in tca

### ISSUE THREAD

**Issue by nhovratov** [TYPO3/styleguide#160]
Should be "disabled" not "disable"

https://github.com/TYPO3/styleguide/blob/4225f009bcc51cf29b7f7cc9d1369f5622fdb542/Configuration/TCA/tx_styleguide_elements_group.php#L154

**Comment by lolli42** [comment]
Good catch. Will fix. Thx!

**Comment by lolli42** [comment]
https://github.com/TYPO3/styleguide/commit/f3a9887165fb4bf5976e7ae3573f388826602266
