### ISSUE TITLE
Introduce a Services.yaml to enable core DI

### ISSUE THREAD

**Issue by alexanderschnitzler** [TYPO3/styleguide#161]
# Feature Request

**Is your feature request related to a problem? Please describe.**

Not a problem yet but it will become one in the future.

**Describe the solution you'd like**

A `Services.yaml` should be in place, especially for the core DI to properly detect extbase controllers which at some point in the near future will no longer be instantiated by the object manager of Extbase. Then, all controllers need to be public services, which currently is not the case without a `Services.yaml`.

**Comment by lolli42** [comment]
I see. Would you like to add an according pull request, or is this task not relevant, yet?

**Comment by lolli42** [comment]
I think it's ok to add patches to styleguide when core is changed in this regard. For the sake of a cleaner issue tracker, I'll close the issue for now, with the option to come back to it later.
