### ISSUE TITLE
Support correct default value null for DateDbTypeDate columns 

### ISSUE THREAD

**Issue by josefglatz** [TYPO3/styleguide#163]
What I understand so far while upgrading a TYPO3 project where I had a column with a db type date field it's necessary (especially with actual versions of mariadb/mysql/...) to have a NULL default value for a date field. This must also be reflected in the TCA. The previously known "feature" that `0000-00-00` as default value fails at least for me after upgrading TYPO3 from 8.7 to 10.4. https://github.com/TYPO3/styleguide/blob/e4b305b29576e3b214de498e202b165c3e35d659/Classes/TcaDataGenerator/FieldGenerator/TypeInputEvalDateDbTypeDate.php#L34

What do you folks think about? Should I prepare a PR for this scenario? The documentation does already mention the "correct way" I think: https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/ColumnsConfig/Type/inputDateTime.html#columns-input-rendertype-inputdatetime

**Comment by ohader** [comment]
Can you please describe what you would like to change (which table, which field, which error message, ..)?

**Comment by lolli42** [comment]
Hey Josef. Hope you're still interested in this! An example for this would be great of course!
