### ISSUE TITLE
Include TCA Examples for type = imageManipulation

### ISSUE THREAD

**Issue by linawolf** [TYPO3/styleguide#178]
# Feature Request

**Is your feature request related to a problem? Please describe.**
It would be great if we had examples to be used in the TCA reference. Current examples are Hand-written:
https://docs.typo3.org/m/typo3/reference-tca/master/en-us/ColumnsConfig/Type/ImageManipulation/Properties/CropVariants.html

**Comment by lolli42** [comment]
https://github.com/TYPO3/styleguide/pull/206
