### ISSUE TITLE
What is the meaning of the button types (e.g. "Primary button" and "Success button")?

### ISSUE THREAD

**Issue by sypets** [TYPO3/styleguide#193]
# Support

![image](https://user-images.githubusercontent.com/13206455/108619657-8b533f00-7426-11eb-8bf5-5369577a84d2.png)

I would understand the "Primary button" to be the most likely used. How is the "Success button" to be used? For example, in Redirects module, the "Filter" is marked in green as the "Success button" here. But that is already the case before an action was performed.

![image](https://user-images.githubusercontent.com/13206455/108619718-e6853180-7426-11eb-8d20-6091ddc0c645.png)

My intention is to better understand how to mark the available buttons.

---

This issue is a question but also a request to add the clarifications into the styleguide - if possible.

**Comment by masi** [comment]
Throughout the backend default is the one used throughout. "primary" is used sometimes for no apparent reason, so is "success". Mostly it seems to me that the dev fancied another colour.

**Comment by masi** [comment]
https://www.tutorialspoint.com/bootstrap/bootstrap_buttons.htm

Here a suggestions is made on how to use success, but I don't find them convincing.

**Comment by sypets** [comment]
@masi Thanks for the link

I see **primary** as useful to emphasize a button. When you have several you often have one that is the most likely action or the one you want to nudge the user towards. GitHub often uses this to mark a button in green (as here, when you write a comment) and I find it useful. In TYPO3 this is already mostly done by the order (most likely button left).

About **success** - I don't see the usecase as much for buttons, but it could emphasize that it is safe to press a button - in contrast to the warning or danger. I just don't get that from the description. 

As for the Filter example above, I would rather use the primary, not the success. But, overusing these styles is not useful, I think. I think it is useful when there is a confusing assortment of buttons where it is not immediately clear, what to press (but that is often already done by the order).

Anyway, if that is used for Filter I think it should be used consistently (and the text also used consistently).

As for the styleguide - it is just a question of using it consistently and providing a helpful quide so it is easy to use consistently.

**Comment by DavidBruchmann** [comment]
one example:
![image](https://user-images.githubusercontent.com/999146/133253035-7e936304-a1d3-4e2d-ba69-26a23c99cb95.png)

**Comment by masi** [comment]
So what now? Go through the BE code an make sure that we have only one "primary" button? Possible.

AFAIR the BE makes also use of a "secondary" colour.

As for "success": perhaps the intention is to use it for the final dismiss button of a modal that has reported a successful completion of a task, ie "you made it!". IMHO a scenario for that I do not a different style.

**Comment by lolli42** [comment]
Hey. styleguide currently gives no pointers which style artifacts are to be used where, and there is currently only a loose understanding about this in the core. I'm unsure on who could pick this up, but I guess it may have to be sorted out and followed in core first. In case that happened, styleguide could give some additional hints on what to use where. As such, I'm going close here for now - if needed, we can always refer to this issue.
