### ISSUE TITLE
Feature request: Style guidelines for icons for extensions

### ISSUE THREAD

**Issue by sypets** [TYPO3/styleguide#210]
# Feature Request

**Is your feature request related to a problem? Please describe.**

My problem is that the extension icons (e.g. in the new content element wizard) are inconsistent. The TYPO3 backend is - in most parts - styled very nicely and this negatively influences the user experience and makes it look like it's in an unfinished state.

**Describe the solution you'd like**

Style guidelines for extension icons: 

- border or not. Which color. Most of the core icons use a grey border, but not all. felogin does not. Also bootstrap_package does not. 

**Describe alternatives you've considered**

I am currently not sure if and how this can be included in the styleguide extension. Or if this is something that could be documented elsewhere. It might also be sufficient to make the icons in the core consistent.

**Additional context**

New content element wizard with core plugin, calendarize, news, ods_osm, tt_address, powermail:

![image](https://user-images.githubusercontent.com/13206455/121397645-d1d89500-c954-11eb-99d9-194dc07b8016.png)

form + felogin:

![image](https://user-images.githubusercontent.com/13206455/121397706-df8e1a80-c954-11eb-8bb7-fee54e7d7161.png)

---

_I hope this is the right place for this. If not, please let me know and I'll take it elsewhere._

_I am not sure if this is the extension to just show the backend functionality. Or if this is also the place to define backend style guidelines._

**Comment by ochorocho** [comment]
Hey :-)

imo, this belongs to the docs e.g. https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/Index.html

Which should include a short guide how to styles/design icons to align with core styles and maybe some example files.

**Comment by sypets** [comment]
@ochorocho Thank you. Sounds like a good plan. 

I can prepare a PR for the docs, probably not just icons specifically, but maybe start with an overview page "TYPO3 backend style guidelines" which also mention this extension and lists some style guidelines and best practices.

**Comment by lolli42** [comment]
Sounds good Sybille. Thx. Guess it's ok to close here.
