### ISSUE TITLE
Use DataHandler::$bypassAccessCheckForRecords when generating data

### ISSUE THREAD

**Issue by ohader** [TYPO3/styleguide#328]
# Bug Report

## Description

```php
$dataHandler = GeneralUtility::makeInstance(DataHandler::class);
$dataHandler->bypassAccessCheckForRecords = true;
```

Explicitly use `bypassAccessCheckForRecords` when generating data by an initialization step.

## Versions

* 12.x
* 11.5.x
* 10.0.x
* 9.2.x

**Comment by ohader** [comment]
Hm... I think I misinterpreted `bypassAccessCheckForRecords` and `isImporting`...

**Comment by lolli42** [comment]
Hey. I think we can close here. I went through some of the DH options and I think generator already uses most important things.
