### ISSUE TITLE
Replace legacy bootstrap classes supported by FontAwesome

### ISSUE THREAD

**Issue by verdure-peuser** [TYPO3/styleguide#341]
# Bug Report

## Prerequisites

* [X] Did you reproduce the problem on TYPO3 core master?
* [X] Did you reproduce the problem on TYPO3 v11.5 LTS?

## Description

FontAwesome provides CSS classes that align with the old Bootstrap v3 classes, which will cause troubles with the removal of FontAwesome. 

If this patch https://review.typo3.org/c/Packages/TYPO3.CMS/+/75342 is applied, a few classes are not available anymore. For example pull-left 

## Steps to Reproduce

1. Apply https://review.typo3.org/c/Packages/TYPO3.CMS/+/75342
2. Open  Styleguide > Typography

**Expected behavior:** 
Colors are aligned left to right

**Actual behavior:** [What actually happened]
Each color is rendered in one line each.

## Versions

dev-main 7b1ccd6

**Comment by sbuerk** [comment]
Thanks for the bug report. If I'm not fully wrong, is this not fixed with the merged #342 ?

**Comment by verdure-peuser** [comment]
@sbuerk the MR doesn't fully adress it.
Within /Resources/Private/Templates/Backend/Typography.html there are still some pull-left classes, leading to missaligend color "blocks".

**Comment by minapok** [comment]
The styles are used in various places in the core and are still provided by a bootstrap mixin.

Applicable locations:
Build/Sources/Sass/backend.scss > Build/Sources/Sass/_minimal.scss > Build/node_modules/bootstrap/scss/mixins/_lists.scss

**Comment by lolli42** [comment]
Thanks Jasmina. I hope it's ok to close here since we think this has been resolved meanwhile, at least in styleguide main/v13.
