### ISSUE TITLE
FileReferences are created incomplete

### ISSUE THREAD

**Issue by christophlehmann** [TYPO3/styleguide#364]
# Bug Report

## Prerequisites

* Current master TYPO3 + Styleguide

## Description

The value of FAL fields are wrong. An image element with 3 file references should have a 3 in the field `image`. Currently it's 0.

This blocks https://review.typo3.org/c/Packages/TYPO3.CMS/+/76820 because the pipeline fails.

## Steps to Reproduce

* ./typo3/sysext/core/bin/typo3 styleguide:generate --create
* See 3 files attached to textpic content element (field `image`).
* See in db the fields value is 0.

Example for creating a file reference: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Fal/UsingFal/ExamplesFileFolder.html#id6

PR follows.

**Comment by lolli42** [comment]
I'll close this issue for the reasons mentioned in https://review.typo3.org/c/Packages/TYPO3.CMS/+/76820
