### ISSUE TITLE
Get rid of inline styles in SVGs

### ISSUE THREAD

**Issue by ohader** [TYPO3/styleguide#377]
* https://github.com/TYPO3/styleguide/tree/main/Resources/Public/Icons
* SVGs use inline styles which should be resolved to static attributes

see https://forge.typo3.org/issues/100140 for the context and how to trigger this in a content-security-policy context

**Comment by benjaminkott** [comment]
![module-styleguide](https://user-images.githubusercontent.com/3243119/231115343-ad878a68-2fdb-4479-add7-c8ccbf741473.svg)

Prepared the SVG
