### ISSUE TITLE
Some text inside example code is unreadable with dark mode active

### ISSUE THREAD

**Issue by PKuhlmay** [TYPO3/styleguide#411]
# Bug Report

## Prerequisites

* [] Did you reproduce the problem on TYPO3 core master?
* [X] Did you reproduce the problem on TYPO3 v12 LTS?
* [] Did you reproduce the problem on TYPO3 v11 LTS?

## Description

When I have dark mode inside my Mac active, some text inside the example code is not readable. The text is white in front of lightgray background.

When having the light mode active, it works.

## Steps to Reproduce

1. Set dark mode inside the Mac OS settings
2. Open the styleguide module and then open (for example) the accordion

**Expected behavior:** 
The text should be black, not white.

**Actual behavior:** 
The text is white, not black.

## Versions
TYPO3 12.4.2
Styleguide dev-main
composer, ddev
![Bildschirmfoto 2023-07-04 um 12 05 18](https://github.com/TYPO3/styleguide/assets/107543296/9b495ef4-ff2f-4b77-97d3-dd66fdbef73c)

**Comment by lolli42** [comment]
We removed prism.js in styleguide-main. This should only be a issue with v12 now.

**Comment by lolli42** [comment]
Hey. With this being "fixed" in current styleguide main, I'll close here for now.
Styleguide v12 is only loosely maintained by us, we'd probably not fix this on our own, except anyone comes up with a PR.
We can re-open or create a new issue in case this is picked up.
