### ISSUE TITLE
section "Avatar" of styleguide does not work

### ISSUE THREAD

**Issue by erredeco** [TYPO3/styleguide#76]
section "Avatar" of styleguide does not work (tested with latest master 8.6-dev); it reports the error:

```
Oops, an error occurred!
Fluid parse error in template Styleguide_action_Avatar_f67162bd947c64ec6ac7b7b03dff844d84d51be2, line 1 at character 1. Error: Unkown Namespace: &lt;be:avatar /&gt; (error code 0). Template source chunk:
```

**Comment by lolli42** [comment]
I don't get it. Which button are you talking of?

**Comment by erredeco** [comment]
Sorry... see attached screenshot

![schermata 2017-01-08 alle 09 50 21](https://cloud.githubusercontent.com/assets/3647646/21748556/13c774ce-d588-11e6-8ec4-381bec8d1b9a.png)

**Comment by lolli42** [comment]
Ok weird. Works for me just fine. Both avatar and button. Would you like to have a more detailed look at you instance on why this may fail for you? i'm running styleguide master (make sure you have it in the correct directory in case you're using a 'linked core'), with core master and current 'composer install'.

**Comment by erredeco** [comment]
"composer install" or "update"?
yes, I am using the "linked core"; the symlinked folder seems correct and  strangely all the other links are working.

**Comment by erredeco** [comment]
I performed composer install, but nothing changed. The error is the same.

**Comment by lolli42** [comment]
If using linked core, the composer install tends to put styleguide into the wrong location (it is then in typo3_src/typo3conf/ext, but not in <document-root>/typo3conf/ext/.

please go to your real document root, then into typo3conf/ext, and have a look if this is really the styleguide version you expect.

**Comment by erredeco** [comment]
I already had in typo3conf/ext/ a symlink to the correct folder inside typo3_src/typo3conf/ext:
the only sections that don't work are Avatar and Buttons, all the others work.

**Comment by lolli42** [comment]
please don't symlink that, but try a full copy instead. this might be a path issue.

**Comment by erredeco** [comment]
Umm no... even after  copying the folder, the error is the same. (I have deleted cache with Install Tool)

**Comment by lolli42** [comment]
Riccardo, that's weird. I'm still unable to reproduce this issue, and totally stuck on how to continue here. Both 8.7 and master work for me without issue. Would you like to give that another shot to see if this is solved for you meanwhile?

**Comment by erredeco** [comment]
Definitely solved. Thank you :)
